// modular-landing-page/app/components/default-products/ProductCard.tsx
'use client';

import { formatPrice } from '@/lib/format';
import { useCurrency, useThemeColors } from '@/store/settings.store';
import { Product } from '@/types/product';
import {
    Eye,
    Heart,
    ShoppingCart,
    Star,
} from 'lucide-react';
import Link from 'next/link';

interface ProductCardProps {
    product: Product;
    onAddToCart?: (product: Product) => void;
    onQuickView?: (product: Product) => void;
    onAddToWishlist?: (product: Product) => void;
}

export function ProductCard({
    product,
    onAddToCart,
    onQuickView,
    onAddToWishlist
}: ProductCardProps) {
    const { symbol } = useCurrency();
    const { primary } = useThemeColors();

    // Helper function to render stars
    const renderStars = (rating: number, totalReviews: number) => {
        const fullStars = Math.floor(rating);
        const hasHalfStar = rating % 1 !== 0;
        const emptyStars = 5 - Math.ceil(rating);

        return (
            <div className="flex items-center gap-2 mb-3">
                <div className="flex items-center gap-0.5">
                    {/* Full stars */}
                    {[...Array(fullStars)].map((_, i) => (
                        <Star
                            key={`full-${i}`}
                            size={16}
                            className="fill-yellow-400 text-yellow-400"
                        />
                    ))}
                    {/* Half star */}
                    {hasHalfStar && (
                        <Star
                            key="half"
                            size={16}
                            className="fill-yellow-400 text-yellow-400"
                            style={{ clipPath: 'inset(0 50% 0 0)' }}
                        />
                    )}
                    {/* Empty stars */}
                    {[...Array(emptyStars)].map((_, i) => (
                        <Star
                            key={`empty-${i}`}
                            size={16}
                            className="fill-none text-yellow-400"
                        />
                    ))}
                </div>
                <span className="text-sm text-gray-600">
                    {rating} / 5 Stars - {totalReviews} Review{totalReviews !== 1 ? 's' : ''}
                </span>
            </div>
        );
    };

    return (
        <div className="flex flex-col h-full">
            {/* Image Container */}
            <div className="relative aspect-[4/5] h-64  rounded-xl overflow-hidden bg-gray-100 mb-4">
                <img
                    src={product.primary_photo || '/placeholder-product.jpg'}
                    alt={product.name}
                    className="w-full h-full object-cover transition-transform duration-500 hover:scale-105"
                />

                {/* Out of Stock Badge */}
                {product.stock === 0 && (
                    <div
                        className="absolute top-4 right-4 text-white text-xs font-bold px-4 py-1.5 rounded-md uppercase tracking-wider shadow-md"
                        style={{ backgroundColor: '#E91E63' }}
                    >
                        Out-Of-Stock
                    </div>
                )}

                {/* Action Icons Bar - Positioned at bottom of image */}
                <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex items-center gap-3 bg-white rounded-full px-4 py-2 shadow-lg">
                    <button
                        onClick={() => onAddToCart?.(product)}
                        className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-gray-50 transition-colors"
                        aria-label="Add to cart"
                        disabled={product.stock === 0}
                    >
                        <ShoppingCart size={20} className="text-gray-700" />
                    </button>
                    <button
                        onClick={() => onQuickView?.(product)}
                        className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-gray-50 transition-colors"
                        aria-label="Quick view"
                    >
                        <Eye size={20} className="text-gray-700" />
                    </button>
                    <button
                        onClick={() => onAddToWishlist?.(product)}
                        className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-gray-50 transition-colors"
                        aria-label="Add to wishlist"
                    >
                        <Heart size={20} className="text-gray-700" />
                    </button>
                </div>
            </div>

            {/* Product Content */}
            <div className="flex flex-col flex-1">
                {/* Category */}
                <p className="text-sm text-gray-600 mb-1.5">
                    {product.category?.name || 'Home Deco'}
                </p>

                {/* Product Title */}
                <h3 className="text-lg font-normal leading-tight mb-1.5">
                    <Link
                        href={`/product-details/${product.name}/${product.id}`}
                        className="hover:opacity-80 transition-opacity"
                        style={{ color: primary }}
                    >
                        {product.name} - <span className="text-gray-400">{product.stock} Left</span>
                    </Link>
                </h3>

                {/* Description */}
                <p className="text-[15px] text-gray-600 leading-relaxed mb-4 line-clamp-4">
                    {product.description || 'Minimalist yet refined, this handcrafted item adds a touch of natural sophistication to any room.'}
                </p>

                {/* Rating Stars */}
                {renderStars(product.rating || 0, product.reviews_count || 0)}

                {/* Price */}
                <div className="mt-auto">
                    <p className="text-xl font-normal text-gray-900">
                        {formatPrice(product.sale_price || product.selling_price, symbol)}
                    </p>
                </div>
            </div>
        </div>
    );
}

// dashboard/src/components/pos/ProductCard.vue
<template>
    <div
         class="bg-white border border-gray-100 rounded-xl shadow-sm hover:shadow-md transition-all duration-300 flex flex-col h-full relative">
        <div class="aspect-square bg-gray-100 rounded-t-lg overflow-hidden max-h-[200px] relative">
            <img :src="product?.primary_photo"
                 :alt="product?.name"
                 class="w-[100%] mx-auto h-full object-cover mix-blend-multiply transition-transform hover:scale-105 duration-500" />
            <div v-if="product?.on_sale"
                 class="absolute top-2 left-2 bg-red-500 text-white px-2 py-1 rounded-md text-xs font-bold">
                SALE
            </div>
            <div v-if="product?.featured"
                 class="absolute top-2 right-2 bg-yellow-500 text-white px-2 py-1 rounded-md text-xs font-bold flex items-center gap-1">
                <el-icon size="12">
                    <StarFilled />
                </el-icon>
                Featured
            </div>
        </div>

        <div class="flex flex-col gap-3 p-4">
            <div>
                <h3 class="text-md font-bold text-gray-800 leading-tight truncate">
                    {{ product?.name }}
                </h3>
                <p class="text-xs text-gray-400 font-light uppercase">
                    {{ product?.category?.name }}
                </p>
            </div>

            <div>
                <div class="flex items-center gap-2">
                    <el-icon v-if="(product?.inventory ?? 0) > 10"
                             class="text-green-500"
                             size="12">
                        <CircleCheckFilled />
                    </el-icon>
                    <el-icon v-else
                             class="text-orange-500"
                             size="12">
                        <WarningFilled />
                    </el-icon>
                    <span class="text-xs font-semibold text-gray-600">
                        {{ product?.inventory ?? 0 }} in stock
                    </span>
                </div>
            </div>

            <div class="flex items-center justify-between pt-3 border-t border-gray-50">
                <div class="flex flex-col gap-1">
                    <div v-if="product?.on_sale && (product?.sale_price ?? 0) > 0"
                         class="flex items-center gap-2">
                        <span class="text-md font-bold text-red-600">{{ formatCurrency(product?.sale_price) }}</span>
                        <span
                              class="text-xs text-gray-400 line-through">{{ formatCurrency(product?.selling_price) }}</span>
                    </div>
                    <span v-else
                          class="text-md font-bold text-gray-900">{{ formatCurrency(product?.selling_price) }}</span>
                    <span v-if="product?.sku"
                          class="text-xs text-gray-400 font-mono">SKU: {{ product?.sku }}</span>
                </div>
                <button @click="handleAddToCart"
                        :disabled="(product?.inventory ?? 0) === 0"
                        :class="[
                            'px-4 py-2 text-xs font-bold border rounded-lg transition-all active:scale-95',
                            (product?.inventory ?? 0) === 0
                                ? 'border-gray-200 bg-gray-100 text-gray-400 cursor-not-allowed'
                                : 'border-gray-200 bg-white hover:bg-gray-900 hover:text-white hover:border-gray-900'
                        ]">
                    {{ (product?.inventory ?? 0) === 0 ? 'Out of Stock' : 'Add to cart' }}
                </button>
            </div>
        </div>
    </div>
</template>

<script setup>
import { CircleCheckFilled, StarFilled, WarningFilled } from '@element-plus/icons-vue'

const props = defineProps({
    product: {
        type: Object,
        required: true
    }
})

const emit = defineEmits(['add-to-cart'])

const handleAddToCart = () => {
    if ((props.product?.inventory ?? 0) > 0) {
        emit('add-to-cart', props.product)
    }
}

const formatCurrency = (amount) => {
    const formatter = new Intl.NumberFormat("en-KE", {
        style: "currency",
        currency: "KES",
        minimumFractionDigits: 2
    })
    return formatter.format(amount ?? 0)
}
</script>
